-- Fitur Backup & Arsip INSAN-J
--
-- Migrasi ini hanya menambahkan metadata arsip, staging restore, audit,
-- transaksi restore/purge, serta pengaman mode pemeliharaan. Tidak ada data
-- operasional yang dihapus ketika migrasi dijalankan.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;

CREATE OR REPLACE FUNCTION public.is_sanitasi_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE id = auth.uid()
      AND lower(role) = 'admin'
  );
$$;

REVOKE ALL ON FUNCTION public.is_sanitasi_admin() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_sanitasi_admin() TO authenticated;

CREATE TABLE IF NOT EXISTS public.data_archives (
  id uuid PRIMARY KEY DEFAULT extensions.gen_random_uuid(),
  schema_version integer NOT NULL DEFAULT 1,
  period_start date NOT NULL,
  period_end date NOT NULL,
  selected_tables text[] NOT NULL,
  table_counts jsonb NOT NULL DEFAULT '{}'::jsonb,
  table_checksums jsonb NOT NULL DEFAULT '{}'::jsonb,
  checksum_sha256 text NOT NULL,
  file_name text NOT NULL,
  file_size_bytes bigint,
  status text NOT NULL DEFAULT 'created'
    CHECK (status IN ('created', 'verified', 'purged', 'restored', 'failed')),
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  verified_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  verified_at timestamptz,
  purged_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  purged_at timestamptz,
  restored_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  restored_at timestamptz,
  last_error text,
  CHECK (period_end >= period_start),
  CHECK (cardinality(selected_tables) > 0)
);

CREATE INDEX IF NOT EXISTS idx_data_archives_created_at
  ON public.data_archives (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_data_archives_status
  ON public.data_archives (status);

-- ID dan versi record disimpan sementara sampai purge. Purge berdasarkan ID
-- snapshot, bukan sekadar tanggal, sehingga record baru setelah backup tidak
-- ikut terhapus.
CREATE TABLE IF NOT EXISTS public.data_archive_items (
  archive_id uuid NOT NULL REFERENCES public.data_archives(id) ON DELETE CASCADE,
  table_name text NOT NULL,
  record_id text NOT NULL,
  record_version timestamptz,
  PRIMARY KEY (archive_id, table_name, record_id)
);

CREATE INDEX IF NOT EXISTS idx_data_archive_items_lookup
  ON public.data_archive_items (archive_id, table_name);

CREATE TABLE IF NOT EXISTS public.data_restore_sessions (
  id uuid PRIMARY KEY DEFAULT extensions.gen_random_uuid(),
  source_archive_id uuid REFERENCES public.data_archives(id) ON DELETE SET NULL,
  schema_version integer NOT NULL,
  checksum_sha256 text NOT NULL,
  period_start date NOT NULL,
  period_end date NOT NULL,
  selected_tables text[] NOT NULL,
  expected_counts jsonb NOT NULL,
  table_checksums jsonb NOT NULL,
  status text NOT NULL DEFAULT 'staging'
    CHECK (status IN ('staging', 'completed', 'aborted', 'failed')),
  created_by uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL DEFAULT (now() + interval '2 hours'),
  completed_at timestamptz,
  last_error text,
  CHECK (period_end >= period_start),
  CHECK (cardinality(selected_tables) > 0)
);

CREATE TABLE IF NOT EXISTS public.data_restore_rows (
  session_id uuid NOT NULL REFERENCES public.data_restore_sessions(id) ON DELETE CASCADE,
  table_name text NOT NULL,
  record_id text NOT NULL,
  row_index integer NOT NULL CHECK (row_index >= 0),
  row_data jsonb NOT NULL,
  PRIMARY KEY (session_id, table_name, record_id),
  UNIQUE (session_id, table_name, row_index)
);

CREATE INDEX IF NOT EXISTS idx_data_restore_rows_order
  ON public.data_restore_rows (session_id, table_name, row_index);

CREATE TABLE IF NOT EXISTS public.admin_audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action text NOT NULL,
  actor_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  archive_id uuid REFERENCES public.data_archives(id) ON DELETE SET NULL,
  restore_session_id uuid REFERENCES public.data_restore_sessions(id) ON DELETE SET NULL,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_created_at
  ON public.admin_audit_logs (created_at DESC);

INSERT INTO public.app_settings (key, value)
VALUES ('operational_maintenance_mode', 'false'::jsonb)
ON CONFLICT (key) DO NOTHING;

-- Hanya Admin yang dapat membaca metadata/audit. Semua penulisan tetap melalui
-- Edge Function dengan Service Role.
ALTER TABLE public.data_archives ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.data_archive_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.data_restore_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.data_restore_rows ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_audit_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS data_archives_select_admin ON public.data_archives;
CREATE POLICY data_archives_select_admin
ON public.data_archives FOR SELECT TO authenticated
USING (public.is_sanitasi_admin());

DROP POLICY IF EXISTS admin_audit_logs_select_admin ON public.admin_audit_logs;
CREATE POLICY admin_audit_logs_select_admin
ON public.admin_audit_logs FOR SELECT TO authenticated
USING (public.is_sanitasi_admin());

CREATE OR REPLACE FUNCTION public.is_operational_archive_table(table_name text)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT table_name = ANY (ARRAY[
    'limbah_padat',
    'limbah_ruangan',
    'limbah_anorganik',
    'pengangkutan_limbah',
    'ruang_bangunan',
    'limbah_medis',
    'pemeriksaan_toilet',
    'pemeriksaan_reservoir',
    'pemeriksaan_gizi'
  ]::text[]);
$$;

REVOKE ALL ON FUNCTION public.is_operational_archive_table(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_operational_archive_table(text) TO service_role;

-- Memblokir mutasi pengguna saat pemeliharaan dan menolak draft lama yang
-- mencoba masuk kembali ke periode yang sudah dipurge. Service Role tetap
-- dapat menjalankan backup/restore/purge.
CREATE OR REPLACE FUNCTION public.guard_operational_archive_write()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, pg_temp
AS $$
DECLARE
  maintenance_enabled boolean := false;
  record_date date;
BEGIN
  IF auth.role() = 'service_role' THEN
    IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
    RETURN NEW;
  END IF;

  SELECT COALESCE(value = 'true'::jsonb, false)
  INTO maintenance_enabled
  FROM public.app_settings
  WHERE key = 'operational_maintenance_mode';

  IF maintenance_enabled THEN
    RAISE EXCEPTION 'Input sementara dinonaktifkan karena Admin sedang menjalankan backup atau pemulihan data.';
  END IF;

  IF TG_OP IN ('INSERT', 'UPDATE') THEN
    record_date := CASE TG_TABLE_NAME
      WHEN 'limbah_padat' THEN NEW.tanggal
      WHEN 'limbah_ruangan' THEN NEW.tanggal
      WHEN 'limbah_anorganik' THEN NEW.tanggal
      WHEN 'pengangkutan_limbah' THEN NEW.tanggal
      WHEN 'ruang_bangunan' THEN NEW.tanggal_pemeriksaan
      WHEN 'limbah_medis' THEN NEW.tanggal_pemeriksaan
      WHEN 'pemeriksaan_toilet' THEN NEW.tanggal_pemeriksaan
      WHEN 'pemeriksaan_reservoir' THEN NEW.tanggal_pemeriksaan
      WHEN 'pemeriksaan_gizi' THEN NEW.tanggal_pemeriksaan
      ELSE NULL
    END;

    IF record_date IS NOT NULL AND EXISTS (
      SELECT 1
      FROM public.data_archives archive
      WHERE archive.status = 'purged'
        AND TG_TABLE_NAME = ANY (archive.selected_tables)
        AND record_date BETWEEN archive.period_start AND archive.period_end
    ) THEN
      RAISE EXCEPTION 'Tanggal % sudah masuk periode arsip. Pulihkan backup melalui Admin jika data perlu dikembalikan.', record_date;
    END IF;
  END IF;

  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.guard_operational_archive_write() FROM PUBLIC;

DO $$
DECLARE
  table_name text;
  trigger_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'limbah_padat',
    'limbah_ruangan',
    'limbah_anorganik',
    'pengangkutan_limbah',
    'ruang_bangunan',
    'limbah_medis',
    'pemeriksaan_toilet',
    'pemeriksaan_reservoir',
    'pemeriksaan_gizi'
  ]::text[]
  LOOP
    IF to_regclass(format('public.%I', table_name)) IS NULL THEN
      RAISE EXCEPTION 'Tabel operasional public.% tidak ditemukan.', table_name;
    END IF;

    trigger_name := format('guard_archive_write_%s', table_name);
    EXECUTE format('DROP TRIGGER IF EXISTS %I ON public.%I', trigger_name, table_name);
    EXECUTE format(
      'CREATE TRIGGER %I BEFORE INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.guard_operational_archive_write()',
      trigger_name,
      table_name
    );
  END LOOP;
END;
$$;

-- Restore seluruh tabel terpilih dalam satu transaksi. Record dengan ID dan
-- isi yang sama dilewati. ID sama dengan isi berbeda membatalkan semuanya.
CREATE OR REPLACE FUNCTION public.admin_commit_restore(
  target_session_id uuid,
  actor_user_id uuid
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, pg_temp
AS $$
DECLARE
  restore_session public.data_restore_sessions%ROWTYPE;
  current_table text;
  expected_count integer;
  staged_count integer;
  conflict_count integer;
  inserted_count integer;
  rows_json jsonb;
  result jsonb := '{}'::jsonb;
  maintenance_enabled boolean := false;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = actor_user_id AND lower(role) = 'admin'
  ) THEN
    RAISE EXCEPTION 'Pelaksana restore bukan administrator aktif.';
  END IF;

  SELECT * INTO restore_session
  FROM public.data_restore_sessions
  WHERE id = target_session_id
  FOR UPDATE;

  IF NOT FOUND THEN RAISE EXCEPTION 'Sesi pemulihan tidak ditemukan.'; END IF;
  IF restore_session.created_by <> actor_user_id THEN RAISE EXCEPTION 'Sesi pemulihan bukan milik Admin ini.'; END IF;
  IF restore_session.status <> 'staging' THEN RAISE EXCEPTION 'Sesi pemulihan sudah tidak aktif.'; END IF;
  IF restore_session.expires_at <= now() THEN RAISE EXCEPTION 'Sesi pemulihan telah kedaluwarsa.'; END IF;

  SELECT COALESCE(value = 'true'::jsonb, false)
  INTO maintenance_enabled
  FROM public.app_settings
  WHERE key = 'operational_maintenance_mode';
  IF NOT maintenance_enabled THEN RAISE EXCEPTION 'Aktifkan mode pemeliharaan sebelum memulihkan data.'; END IF;

  FOREACH current_table IN ARRAY restore_session.selected_tables
  LOOP
    IF NOT public.is_operational_archive_table(current_table) THEN
      RAISE EXCEPTION 'Tabel % tidak diizinkan untuk pemulihan.', current_table;
    END IF;

    expected_count := COALESCE((restore_session.expected_counts ->> current_table)::integer, 0);
    SELECT count(*) INTO staged_count
    FROM public.data_restore_rows staged
    WHERE staged.session_id = target_session_id AND staged.table_name = current_table;

    IF staged_count <> expected_count THEN
      RAISE EXCEPTION 'Jumlah staging tabel % tidak sesuai: % dari %.', current_table, staged_count, expected_count;
    END IF;

    EXECUTE format(
      'SELECT count(*) FROM public.data_restore_rows staged JOIN public.%I target ON target.id::text = staged.record_id WHERE staged.session_id = $1 AND staged.table_name = $2 AND to_jsonb(target) IS DISTINCT FROM staged.row_data',
      current_table
    ) INTO conflict_count USING target_session_id, current_table;

    IF conflict_count > 0 THEN
      RAISE EXCEPTION 'Ditemukan % konflik ID pada tabel %. Tidak ada data yang dipulihkan.', conflict_count, current_table;
    END IF;
  END LOOP;

  FOREACH current_table IN ARRAY restore_session.selected_tables
  LOOP
    expected_count := COALESCE((restore_session.expected_counts ->> current_table)::integer, 0);
    inserted_count := 0;

    IF expected_count > 0 THEN
      SELECT jsonb_agg(row_data ORDER BY row_index)
      INTO rows_json
      FROM public.data_restore_rows staged
      WHERE staged.session_id = target_session_id AND staged.table_name = current_table;

      EXECUTE format(
        'INSERT INTO public.%I SELECT restored.* FROM jsonb_populate_recordset(NULL::public.%I, $1) AS restored ON CONFLICT (id) DO NOTHING',
        current_table,
        current_table
      ) USING rows_json;
      GET DIAGNOSTICS inserted_count = ROW_COUNT;
    END IF;

    result := result || jsonb_build_object(
      current_table,
      jsonb_build_object(
        'expected', expected_count,
        'inserted', inserted_count,
        'skipped', expected_count - inserted_count
      )
    );
  END LOOP;

  UPDATE public.data_restore_sessions
  SET status = 'completed', completed_at = now(), last_error = NULL
  WHERE id = target_session_id;

  IF restore_session.source_archive_id IS NOT NULL THEN
    UPDATE public.data_archives
    SET status = CASE WHEN status = 'purged' THEN 'restored' ELSE status END,
        restored_by = actor_user_id,
        restored_at = now(),
        last_error = NULL
    WHERE id = restore_session.source_archive_id;
  END IF;

  INSERT INTO public.admin_audit_logs (
    action, actor_id, archive_id, restore_session_id, details
  ) VALUES (
    'data_restored', actor_user_id, restore_session.source_archive_id, target_session_id,
    jsonb_build_object(
      'period_start', restore_session.period_start,
      'period_end', restore_session.period_end,
      'tables', restore_session.selected_tables,
      'result', result
    )
  );

  DELETE FROM public.data_restore_rows WHERE session_id = target_session_id;
  RETURN result;
END;
$$;

REVOKE ALL ON FUNCTION public.admin_commit_restore(uuid, uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_commit_restore(uuid, uuid) FROM anon;
REVOKE ALL ON FUNCTION public.admin_commit_restore(uuid, uuid) FROM authenticated;
GRANT EXECUTE ON FUNCTION public.admin_commit_restore(uuid, uuid) TO service_role;

-- Purge memakai daftar ID snapshot dan memverifikasi versi record sebelum satu
-- baris pun dihapus. Seluruh tabel diproses dalam transaksi RPC yang sama.
CREATE OR REPLACE FUNCTION public.admin_purge_archive(
  target_archive_id uuid,
  actor_user_id uuid
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, pg_temp
AS $$
DECLARE
  archive_record public.data_archives%ROWTYPE;
  current_table text;
  expected_count integer;
  snapshot_count integer;
  current_count integer;
  changed_count integer;
  deleted_count integer;
  result jsonb := '{}'::jsonb;
  maintenance_enabled boolean := false;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = actor_user_id AND lower(role) = 'admin'
  ) THEN
    RAISE EXCEPTION 'Pelaksana penghapusan bukan administrator aktif.';
  END IF;

  SELECT * INTO archive_record
  FROM public.data_archives
  WHERE id = target_archive_id
  FOR UPDATE;

  IF NOT FOUND THEN RAISE EXCEPTION 'Arsip tidak ditemukan.'; END IF;
  IF archive_record.status <> 'verified' THEN RAISE EXCEPTION 'Backup harus berstatus terverifikasi sebelum data dihapus.'; END IF;

  SELECT COALESCE(value = 'true'::jsonb, false)
  INTO maintenance_enabled
  FROM public.app_settings
  WHERE key = 'operational_maintenance_mode';
  IF NOT maintenance_enabled THEN RAISE EXCEPTION 'Aktifkan mode pemeliharaan sebelum menghapus data.'; END IF;

  FOREACH current_table IN ARRAY archive_record.selected_tables
  LOOP
    IF NOT public.is_operational_archive_table(current_table) THEN
      RAISE EXCEPTION 'Tabel % tidak diizinkan untuk penghapusan.', current_table;
    END IF;

    expected_count := COALESCE((archive_record.table_counts ->> current_table)::integer, 0);
    SELECT count(*) INTO snapshot_count
    FROM public.data_archive_items item
    WHERE item.archive_id = target_archive_id AND item.table_name = current_table;
    IF snapshot_count <> expected_count THEN
      RAISE EXCEPTION 'Snapshot tabel % tidak lengkap: % dari %.', current_table, snapshot_count, expected_count;
    END IF;

    EXECUTE format(
      'SELECT count(*) FROM public.%I target JOIN public.data_archive_items item ON item.record_id = target.id::text WHERE item.archive_id = $1 AND item.table_name = $2',
      current_table
    ) INTO current_count USING target_archive_id, current_table;
    IF current_count <> expected_count THEN
      RAISE EXCEPTION 'Data tabel % berubah atau sudah terhapus setelah backup. Buat backup baru.', current_table;
    END IF;

    EXECUTE format(
      'SELECT count(*) FROM public.%I target JOIN public.data_archive_items item ON item.record_id = target.id::text WHERE item.archive_id = $1 AND item.table_name = $2 AND target.waktu_input IS DISTINCT FROM item.record_version',
      current_table
    ) INTO changed_count USING target_archive_id, current_table;
    IF changed_count > 0 THEN
      RAISE EXCEPTION 'Ada % record tabel % yang berubah setelah backup. Buat backup baru.', changed_count, current_table;
    END IF;
  END LOOP;

  FOREACH current_table IN ARRAY archive_record.selected_tables
  LOOP
    EXECUTE format(
      'DELETE FROM public.%I target USING public.data_archive_items item WHERE item.archive_id = $1 AND item.table_name = $2 AND target.id::text = item.record_id',
      current_table
    ) USING target_archive_id, current_table;
    GET DIAGNOSTICS deleted_count = ROW_COUNT;
    result := result || jsonb_build_object(current_table, deleted_count);
  END LOOP;

  UPDATE public.data_archives
  SET status = 'purged', purged_by = actor_user_id, purged_at = now(), last_error = NULL
  WHERE id = target_archive_id;

  INSERT INTO public.admin_audit_logs (action, actor_id, archive_id, details)
  VALUES (
    'data_purged', actor_user_id, target_archive_id,
    jsonb_build_object(
      'period_start', archive_record.period_start,
      'period_end', archive_record.period_end,
      'deleted_counts', result
    )
  );

  -- ID snapshot tidak lagi diperlukan setelah purge. Ringkasan dan checksum
  -- tetap berada di data_archives/admin_audit_logs.
  DELETE FROM public.data_archive_items WHERE archive_id = target_archive_id;
  RETURN result;
END;
$$;

REVOKE ALL ON FUNCTION public.admin_purge_archive(uuid, uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_purge_archive(uuid, uuid) FROM anon;
REVOKE ALL ON FUNCTION public.admin_purge_archive(uuid, uuid) FROM authenticated;
GRANT EXECUTE ON FUNCTION public.admin_purge_archive(uuid, uuid) TO service_role;

COMMIT;

-- Pemeriksaan sesudah migrasi (read-only)
SELECT tablename, rowsecurity
FROM pg_tables
WHERE schemaname = 'public'
  AND tablename IN (
    'data_archives', 'data_archive_items', 'data_restore_sessions',
    'data_restore_rows', 'admin_audit_logs'
  )
ORDER BY tablename;

SELECT key, value
FROM public.app_settings
WHERE key = 'operational_maintenance_mode';
